### ISSUE TITLE
行号的生成逻辑问题

### ISSUE THREAD

**Issue by ForeUP** [jl15988/joplin-plugin-code-perfect#10]
您好，我自己在css中修改了代码块的字体与行高与padding。
使用您的插件后发现行号和代码行不匹配，并且经过测试，只有这三项都不设定时才不会出错。

padding是用了给没设定代码语言的代码块进行缩进的，行高和字体都是为了看起来更舒服，
所以，如果这三项我都要设置的情况下，请问有办法可以修复这个问题吗？

![Image](https://github.com/user-attachments/assets/7c418214-6348-406b-8bdc-0ef112029b19)

下面是代码块css的定义：
```css
/* 代码块 */
pre, .hljs {
  font-family: "Cascadia Code", Consolas, "Microsoft YaHei", monospace !important;
  padding: 10px;
  font-size: 15px !important;
  overflow: scroll !important;
  line-height: 1.26em;
}
```
